// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace DKH.Demo.Plugins.SamplePlugin.Data.Migrations;

[DbContext(typeof(SamplePluginDbContext))]
internal partial class SamplePluginDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

        modelBuilder.Entity("DKH.Demo.Plugins.SamplePlugin.Data.Entities.PluginSetting", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("TEXT");

            b.Property<string>("Key")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("TEXT");

            b.Property<string>("Value")
                .IsRequired()
                .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("Key")
                .IsUnique();

            b.ToTable("plugin_settings", (string)null);
        });
#pragma warning restore 612, 618
    }
}
